#!/usr/bin/env python
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004
#
# Copyright (C) 2022 cubercsl <2014cais01 at gmail dot com>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.

from pathlib import Path

root = Path(__file__).parent.parent


def txt_file(name):
    with open(root / name) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                token, code, *_ = line.split()  # assume the weight is sorted desc
                yield code, token


def yaml_file(name):
    with open(root / name) as f:
        data = False
        for line in f:
            line = line.strip()
            if data and line:
                token, code, *_ = line.split()
                yield code, token
            if not data and line == '...':
                data = True


header = ''';fcitx Version 0x03 Table file
键码=abcdefghijklmnopqrstuvwxyz;'
码长=4
构词=^
[组词规则]
e2=p11+p12+p21+p22
e3=p11+p21+p31+p32
a4=p11+p21+p31+n11
[数据]'''


def main():
    print(header)
    for code, word in yaml_file('flypydz.dict.yaml'):
        print(f'^{code[:2]} {word}')
    for f in (
        'flypy.user.top',
        # 'flypy.full.top',
        'flypy.fast.symbols',
        'flypy.primary',
        # 'flypy.secondary.short.code',
        'flypy.secondary',
        'flypy.web',
        'flypy.emoji',
        'flypy.symbols',
        'flypy.wechat',
        'flypy.whimsicality',
        'flypy.primary.short.word',
        # 'flypy.full.char',
        # 'flypy.full',
        'flypy.user'
    ):
        for code, word in yaml_file(Path('flypy') / f'{f}.dict.yaml'):
            print(f'{code} {word}')


if __name__ == '__main__':
    main()
