name: ci

on:
  push:
    branches: [master]
    tags:
      - "v*"
  pull_request: 
    branches: [master]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make python3 libime-bin
      - name: Build
        run: |
          make && make dist
          make -C fcitx5
          tar -C fcitx5 -zcvf fcitx5-table-flypy.tar.gz flypy.{conf,dict,txt}
          cd fcitx5 && zip ../fcitx5-table-flypy.zip flypy.{conf,dict,txt}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: flypy
          path: |
            rime-flypy.tar.gz
            fcitx5-table-flypy.tar.gz
            fcitx5-table-flypy.zip

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: flypy
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          files: |
            rime-flypy.tar.gz
            fcitx5-table-flypy.tar.gz
            fcitx5-table-flypy.zip
    
